### ISSUE TITLE
server bind/unbind 的时候，如果server没有设置OpenToCloseCollectSeconds或OpenToCloseCollectSeconds=0，proxy会挂掉

### ISSUE THREAD

**Issue by weisd** [fagongzi/gateway#14]
server bind、unbind 的时候，如果server没有设置OpenToCloseCollectSeconds或OpenToCloseCollectSeconds=0， proxy会挂掉，

是不是创建server的时候做参数验证或给默认值

```
panic: non-positive interval for NewTicker

goroutine 58 [running]:
time.NewTicker(0x0, 0xc420011ad0)
	/usr/local/go/src/time/tick.go:23 +0x1b4
github.com/fagongzi/gateway/pkg/model.(*Analysis).AddRecentCount(0xc4200166e0, 0xc4201938b0, 0xe, 0x0)
	/Users/weisd/gopath/src/github.com/fagongzi/gateway/pkg/model/analysis.go:154 +0x1ce
github.com/fagongzi/gateway/pkg/model.(*RouteTable).UpdateServer(0xc420060310, 0xc4201962d0, 0x0, 0x0)
	/Users/weisd/gopath/src/github.com/fagongzi/gateway/pkg/model/ruletable.go:238 +0x155
github.com/fagongzi/gateway/pkg/model.(*RouteTable).doReceiveServer(0xc420060310, 0xc4201bf380)
	/Users/weisd/gopath/src/github.com/fagongzi/gateway/pkg/model/ruletable.go:586 +0x6c
github.com/fagongzi/gateway/pkg/model.(*RouteTable).doEvtReceive(0xc420060310)
	/Users/weisd/gopath/src/github.com/fagongzi/gateway/pkg/model/ruletable.go:529 +0x19d
created by github.com/fagongzi/gateway/pkg/model.(*RouteTable).watch
	/Users/weisd/gopath/src/github.com/fagongzi/gateway/pkg/model/ruletable.go:514 +0xb8
```

**Comment by weisd** [comment]
另外admin后面操作， api返回错误时是不是提示一下，现在什么都不显示

**Comment by zhangxu19830126** [comment]
是的，admin管理界面没有做数据校验。这是个bug

**Comment by weisd** [comment]
@zhangxu19830126 这个项目很棒，我什么我可以帮忙的吗？加个好友一起学习啊

**Comment by zhangxu19830126** [comment]
加个微信，13675153174
